### ISSUE TITLE
Different parsed queries.

### ISSUE THREAD

**Issue by modassar81** [tballison/lucene-addons#10]
Hi Tim,

Currently I am using java 5.x and trying to migrate to Solr 6.x with lucene-addons-lucene6.1-0.1.
I noticed a difference in parsed queries in both the versions.
This is causing lesser number of documents match in solr 6.x which is not expected.

E.g.
Query : `f:3d`
Solr 5.x
Parsed Query : `+(((f:3d f:3) f:d)~2)`
Solr 6.x
Parsed Query : `+(+Synonym(f:3 f:3d) +f:d)`

Similarly for:
Query : `f:"3d print"`
Solr 5.x
Parsed Query : `+spanNear([spanOr([spanOr([f:3d, f:3]), f:d]), f:print], 0, true)`
Solr 6.x
Parsed Query : `+spanNear([f:d, f:print], 0, true)`

I noticed this issue for the queries with a term which gets broken in WordDelimiterFilter.

Please help me understand and resolve this issue.

Thanks,
Modassar

**Comment by tballison** [comment]
I'll take a look.

Any idea why the "3" is dropped entirely from the second query but not the first?

**Comment by modassar81** [comment]
Thanks Tim for your response.

Per my understanding it may be because of the difference in parsed query in solr 6.x.

Following is the analysis change we use.

`<tokenizer class="solr.WhitespaceTokenizerFactory"/>`
`<filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt"/>`
`<filter class="solr.WordDelimiterFilterFactory" generateWordParts="1" generateNumberParts="1" catenateWords="1" catenateNumbers="1" catenateAll="1" splitOnCaseChange="1" preserveOriginal="1"/>`
`<filter class="solr.ICUFoldingFilterFactory"/>`
`<filter class="solr.PatternReplaceFilterFactory" pattern="<PATTERN>" replacement="<REPLACEMENT>"/>`
`<filter class="solr.KStemFilterFactory"/>`
`<filter class="solr.RemoveDuplicatesTokenFilterFactory"/>`

Best,
Modassar

**Comment by tballison** [comment]
I'm assuming your defaultOperator is "AND" in 6.X?

**Comment by tballison** [comment]
With your analysis chain, I get the same output whether I use the SpanQueryParser or the classic parser on "3d" with a defaultOperator = "AND"
+(+Synonym(f:3 f:3d) +f:d)

So, this is ok?  Find documents that contain "3 or 3d" and "d"?  Or, what should the output be if not what the classic parser returns?

On the second query, I'm able to replicate the dropping of the "3" in 3d.  I'll look more closely at that one.

**Comment by tballison** [comment]
Ok, y, I found the bug in 6.x that dropped the 3 in "3d print".  The code that handled BooleanQueries was only expecting a TermQuery or another BooleanQuery, so it was not handling the new SynonymQuery.  The current output is:

> spanNear([spanOr([f1:3, f1:3d, f1:d]), f1:print], 0, true)

This is what you'd expect, no?

**Comment by modassar81** [comment]
Please find my comments below.

I'm assuming your defaultOperator is "AND" in 6.X?
Yes! the default operator is set to AND.

So, this is ok?
The default parser in Solr 5.x has parsed the query `f:3d` to `+(((f:3d f:3) f:d)~2)` but the same query is being parsed as `+(+Synonym(f:3 f:3d) +f:d)` in Solr 6.x. I am not sure why this change?
Can you please help me understand it? I could not find any documentation or link explaining about the change.

 This is what you'd expect, no?
I think it should be parsed as`+spanNear([spanOr([spanOr([f:3d, f:3]), f:d]), f:print], 0, true)` as it is doing in Solr 5.x.

**Comment by tballison** [comment]
First, thank you for opening this issue.  You identified a bug in my code that was dropping the 3!  That's now fixed.

> The default parser in Solr 5.x has parsed the query f:3d to +(((f:3d f:3) f:d)~2) but the same query is being parsed as +(+Synonym(f:3 f:3d) +f:d) in Solr 6.x. I am not sure why this change?
Can you please help me understand it? I could not find any documentation or link explaining about the change.

SynonymQuery was introduced in 6.x.  I'm not familiar with why, but from the javadocs, it looks to be for efficiency and for more consistent scoring(?).  So, functionally, it should be the same as spanOr, or in this case Boolean "or".  But you're right, why did the proximity operator disappear.  K, I'll take a look.

>I think it should be parsed as+spanNear([spanOr([spanOr([f:3d, f:3]), f:d]), f:print], 0, true) as it is doing in Solr 5.x.

This is logically the same as 
`spanNear([spanOr([f1:3, f1:3d, f1:d]), f1:print], 0, true) `

The reason that these are different structurally has to do with how Lucene's QueryBuilder's createFieldQuery is creating different underlying queries in 5.x vs 6.x

**Comment by modassar81** [comment]
Thanks for the fix.

**Comment by tballison** [comment]
I did make the one fix, but I'm still troubled by:

> Query : f:3d
Solr 5.x
Parsed Query : +(((f:3d f:3) f:d)~2)
Solr 6.x
Parsed Query : +(+Synonym(f:3 f:3d) +f:d)

I'm not able to reproduce this difference now with my 5.5-0.2 branch compared with my 6.1-0.1 branch.  Are you?

I think the difference has to do with whether "autoGeneratePhraseQueries" is set to true or not.

To confirm, though, you're ok with this?
