### ISSUE TITLE
For clarification on the parsing of query.

### ISSUE THREAD

**Issue by modassar81** [tballison/lucene-addons#16]
Hi Tim,

I understand that to search "/" , as is,  we need to escape it in any query term. E.g. q=start\/stop.
But what if the term is under double quotes. E.g Can user expect an exact match for "start/stop" if given in double quotes provided analysis chain has not tokenized start/stop?

Thanks,
Modassar

**Comment by tballison** [comment]
This is tricky. You'd want single quotes to bypass analysis.  Or, you'd want to escape '/'.  Anything between double quotes is treated as a phrase, and the unescaped '/' would be interpreted as the start of a regex term...you'll get a parse exception with "start/stop".

**Comment by modassar81** [comment]
Hi Tim,

We need to escape / with either single quotes or backslash like "start'/'stop" or "start\\/stop".
fl:"start'/'stop" is parsed to +spanNear([fl:start, fl:, fl:stop]
where as 
fl:"start\\/stop" is parsed to +tto:start/stop.
The first query searches start / stop , start - stop but not start/stop whereas the second query searches only start/stop.
Please help me understand the difference in both the escaping of /. I want to get all the documents containing start/stop.

Thanks,
Modassar

**Comment by tballison** [comment]
I'm sorry I may not be understanding.

First, the point about single quotes was that they should go around the full token, so if `start/stop` is something that you want to treat as a single token, it would be `"'start/stop'"`.

I'm not clear, though, on what you're trying to get back....sorry!

Is it the case that you only want documents that contain a single token `start/stop`?

If so, it looks like `"start\\/stop"` is getting you what you need.

If you want to get documents that contain any one of three tokens `start/stop` or `start` or `stop`, then you'd do `"start\\/stop start stop"`, right?

I'm sorry I'm not understanding!

**Comment by modassar81** [comment]
Thanks for the response Tim.

The way of escaping `"start'/'stop"` was wrong so I was getting unexpected result.
As per your last comment it should be `""start/stop""`. Using this I am getting the expected result.

What I now see that `"'start/stop'"` and `"start\\/stop"` are yielding same set of results.
Are these both correct ways of escaping?

Best,
Modassar

**Comment by modassar81** [comment]
Can you please help me with following query too?
I am getting a `org.apache.lucene.queryparser.classic.ParseException: Didn't find matching: '` for `q=user's`. I understand single quote is a part of query syntax but how I can search terms with apostrophe.

Best,
Modassar

**Comment by tballison** [comment]
'user''s'

**Comment by tballison** [comment]
> Are these both correct ways of escaping?
Y.

**Comment by modassar81** [comment]
Thanks Tim.
