### ISSUE TITLE
Wrong number of results.

### ISSUE THREAD

**Issue by modassar81** [tballison/lucene-addons#19]
Hi Tim,
How are you?

I am getting a wrong count of search where the number of matches is greater than one of actual number of document matched. When i debugged I am getting a sense that following issue might be causing this. 
`https://issues.apache.org/jira/browse/LUCENE-6796`

Thought of confirming with you if this issue can increase the count of match. If my assumption is correct I will share the query and other details to reproduce it with you as currently I am having only the query and not the test case which can reproduce it.

Thanks,
Modassar

**Comment by tballison** [comment]
Y, please do share query.  I'm aware of [LUCENE-7398](https://issues.apache.org/jira/browse/LUCENE-7398)...which may be related.  I think the highlighter is a different issue, but I'll help you figure that out with more info... Thank you!

**Comment by modassar81** [comment]
Hi Tim,
Sorry for the late reply. I will create a test case to reproduce this issue and share with you as soon as possible.

Thanks,
Modassar

**Comment by tballison** [comment]
@modassar81 any work to be done here?

**Comment by modassar81** [comment]
Sorry Tim for late reply.

I am yet to write a test class to reproduce it. I will write it and share with you.
If you suggest I will close this issue for now.

Best,
Modassar

**Comment by modassar81** [comment]
Sorry for late reply Tim. It came out to be a data issue at our end and not a Solr bug.
Thanks for your support,

Best,
Modassar
