### ISSUE TITLE
Query complexity scorer.

### ISSUE THREAD

**Issue by modassar81** [tballison/lucene-addons#20]
Hi Tim,

I am trying to find possible complexity of a query heuristically/ based on
learning and provide a score to it before it is actually sent to Solr for
execution.
The query may contain wildcards, complex phrases, phrases with wildcards.

The approach is to assign a number to each part of a query and then get an
accumulated normalized score. It can also be extended further for scoring
based on pattern of queries.
The scorer is unaware of Solr, index size and possible complexity involved
in finding a match due to which a simple looking query is scored less
complex but takes more time in Solr than a query looking more complex.

Kindly share your suggestions and inputs on the parameters to consider and
how it can be implemented. 

Best,
Modassar

**Comment by tballison** [comment]
I'm not quite sure what your ultimate goal is.  If you're trying to estimate whether a query will take forever to return, I don't see a way that you could do that without reference to the index.

I can easily see walking the query's parse tree and assigning scores to wild card, fuzzy, etc.  However, I have no idea what scores to assign, without reference to the index.  I suspect that the statistical distribution of the terms in the index would have an overwhelming affect on performance.

For example, "t*" in a largely English index would likely yield far more results than "z*".  Without any reference to an index or any other outside knowledge, all you'd see would be a prefix query of length 1. 

Again, a proximity query "cat dog"~1000 could require quite a bit more computation than, say "cat dog"~2.  However, if you're indexing only tweets, there may not be a significant performance difference.

If you have access to a "training" index, then, y, I could see applying machine learning to learn the appropriate weights for given query features if you're trying to predict return time.  That makes the assumption that your training index is similar to your test/production index.

Sorry, this isn't very helpful.

**Comment by modassar81** [comment]
Thanks for your comment Tim.

I have written one heuristic based class which is at-least giving me a complex score for complex queries.
It needs some more fine tuning. I am planning to extend it to machine learning.

Best,
Modassar

**Comment by tballison** [comment]
Great.  Let me know how that goes.  BTW, have you looked at Luwak -- https://github.com/flaxsearch/luwak?

**Comment by dsmiley** [comment]
Just curious @tballison what does Luwak have to do with this GH project or this issue?

**Comment by tballison** [comment]
@dsmiley, my guess was that if @modassar81 is using my query parser to generate very complex queries -- complex enough that he is building his own heuristic measurement of complexity -- he may want to look at Luwak which, as you know, is designed to process very complex queries efficiently.

**Comment by dsmiley** [comment]
AFAIK, Luwak's purpose in life is to handle an upside-down use case for search -- static queries, documents coming in -- return matching queries per document.  Yes some of those queries might be _complex_ but for that matter, so might they be to a regular Lucene search app.

**Comment by tballison** [comment]
Agreed, my thought was that Luwak optimizes the query based on the document, and should be more efficient than the SpanQueries that I'm generating...if the use case is percolation/upside-down search.  So, right, that's the key part.

**Comment by tballison** [comment]
Finally found the slide I was trying to remember (slide 19): [Luwak on slideshare](https://www.slideshare.net/charliejuggler/lucene-solrlondonug-nov28-2014-turning-search-upside-down?qid=f584fc6d-06b7-40d6-9de7-47d6ded322b4&v=&b=&from_search=1)
