### ISSUE TITLE
Issue in regex query.

### ISSUE THREAD

**Issue by modassar81** [tballison/lucene-addons#21]
Hi Tim,

I am trying following two regex queries but getting matches in only one of them.

`Query : fl:/networ.{0,1}/`
`"parsedquery_toString": "boost(+(),int(doc_wt))",`
`Matches zero.`

`Query : fl:"/networ.{0,1}/"`
`"parsedquery_toString": "boost(+SpanMultiTermQueryWrapper(fl:/networ.{0,1}/),int(doc_wt))",`
`"matches": 689839,`

Is it that the regex queries must be enclosed in double quotes in SpanQueryParser.

Regards,
Modassar

**Comment by tballison** [comment]
> Is it that the regex queries must be enclosed in double quotes in SpanQueryParser.

No. This looks like a bug.  Thank you for raising this!  I'll take a look.

**Comment by tballison** [comment]
Hmmm... I'm not able to reproduce this.  Which version of the SpanQueryParser are you using?  Which version of Lucene?  What does your AnalyzerChain look like?
`
  public void testRegexWCurlyBrackets() throws Exception {
    Query q = PARSER.parse("f1:/networ.{0,1}/");
    System.out.println(q + " : " + q.getClass());
  }
`
yields: 
`
f1:/networ.{0,1}/ : class org.apache.lucene.search.RegexpQuery
`

That query also returns the correct documents:
`
compareHits("f1:/qui.{0,2}/", 0,1,2);
`

I get the same behavior whether or not I put the query in double quotes.  

As I look through the code, I now remember that the parser runs regex terms through the MultitermAnalyzer.  Is there a chance that you are using a different multiterm analyzer for the first query than for the second query?

**Comment by modassar81** [comment]
Thanks Tim for your response.

I found the issue. It was a piece of code in my class which was actually stripping the `/` from the regex queries.

Best,
Modassar

**Comment by tballison** [comment]
Ah, ok.  Thank you for closing the loop.  Let me know what else you find!
