### ISSUE TITLE
Right version of lucene-addons.

### ISSUE THREAD

**Issue by modassar81** [tballison/lucene-addons#24]
Hi Tim,

I am migrating to Lucene/Solr-6.5.1 for which I have used following lucene-addons branch. https://github.com/tballison/lucene-addons/tree/6.5-0.1

Please let me know if I am using right branch.

Thanks,
Modassar

**Comment by modassar81** [comment]
Hi Tim,

Kindly provide your response to the above question.

Thanks,
Modassar

**Comment by tballison** [comment]
Sorry for the delay.  Yes.  Looks like 6.6 will be out soon! :)

**Comment by modassar81** [comment]
Thanks Tim.
