### ISSUE TITLE
ClassNotFoundException on 6.6 branch

### ISSUE THREAD

**Issue by sjwoodard** [tballison/lucene-addons#28]
Hi, I just loaded the 6.6 branch, and noticed the package name changed to org.tallison.solr.search. Can you update the docs to reflect that? Otherwise, you'll get a class not found error.

Thanks!

**Comment by tballison** [comment]
Doh!  Sorry, what was the pkg name before?  Is this for the solr-5410 module?

**Comment by sjwoodard** [comment]
PR: https://github.com/tballison/lucene-addons/pull/31

**Comment by tballison** [comment]
Thank you!
