### ISSUE TITLE
Recursive query doesn't handle AND operator properly

### ISSUE THREAD

**Issue by sjwoodard** [tballison/lucene-addons#30]
If I try to search [(foo bar) (baz qux)]~5, there is an implicit OR operator between foo/bar and baz/qux. So, if I put an explicit AND operator in like [(foo AND bar) (baz AND qux)]~5, then AND gets used as a query term instead of an operator.

I also tried {!span q.op=AND}, but that doesn't have any impact to query terms once they're inside the [ ] brackets.

**Comment by sjwoodard** [comment]
Maybe the question is... should the q.op parameter be respected inside the brackets?

I'm looking in the SpanQueryParser in Lucene-5205 and trying to find where this should take place. On line 274-288, you have this:
`
      //if or clause, recurse through tokens
      if (token instanceof SQPOrClause) {
        //recurse!
        SQPOrClause tmpOr = (SQPOrClause)token;
        q = parseRecursively(tokens, currField, tmpOr);
        //if it isn't already boosted, apply the boost from the token
        if (!(q instanceof BoostQuery) && !(q instanceof SpanBoostQuery) &&
            tmpOr.getBoost() != null) {
          if (q instanceof SpanQuery) {
            q = new SpanBoostQuery((SpanQuery)q, tmpOr.getBoost());
          } else {
            q = new BoostQuery(q, tmpOr.getBoost());
          }
        }
        i = tmpOr.getTokenOffsetEnd();
`
Should it be doing the same thing for the AND clause?

**Comment by tballison** [comment]
Y, give that this is happening _inside_ a SpanNearQuery, I don't think the `q.op` should be operative.  If you want "or", use this: 

`[(foo bar) (baz qux)]~5` 

if you want "and", use this:
`["foo bar" "baz qux"]~5`
or even
`[foo bar baz qux]~5`

WDYT?

**Comment by tballison** [comment]
And, you're right, once inside a span, the boolean operators don't work.

**Comment by sjwoodard** [comment]
OK, got it. I thought the operators would still work inside the span.

Here's a better example of the issue, `[foo (bar AND baz)]~5`, which I guess could be rewritten as `[foo bar]~5 OR [foo baz]~5`

I'll go ahead and close it. Thanks for the clarification!

**Comment by tballison** [comment]
I'm not sure I understand what you're trying to search for...sorry.

`[foo (bar AND baz)]~5` ... I interpret as "find foo within 5 words of bar and baz", which can be written as just `[foo bar baz]~5`...right?  And, of course, technically, that's find the three words within 5 words' slop, and "find foo within five words of bar and baz" would also want to retrieve "bar x x x x foo x x x x baz", so just bump the 5->10 :)

If you want to find `"foo bar"~5` and  `"foo baz"~5`, that'd be `[foo bar]~5 AND [foo baz]~5` ...right?
