### ISSUE TITLE
ant dist fails.

### ISSUE THREAD

**Issue by modassar81** [tballison/lucene-addons#4]
Hi Tim,
The way I integrate SpanQueryParser is the package is added under Lucene/queryparser package.
Then a full build is done locally using ant compile and ant dist. Till the 5.2.1 I was not getting any build issue. But when I tried the same with Lucene/Solr-5.4.1 the build is failing for "ant dist" with following message. I am using lucene-addons-lucene5.4on-0.1.

  [javadoc] Constructing Javadoc information...
  [javadoc] Standard Doclet version 1.7.0_91
  [javadoc] Building tree for all the packages and classes...
  [javadoc] /lucene_solr_5_4_0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParserBase.java:181: warning - @return tag has no arguments.
  [javadoc] /lucene_solr_5_4_0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParserBase.java:333: warning - @return tag has no arguments.
  [javadoc] Building index for all the packages and classes...
  [javadoc] Building index for all classes...
  [javadoc] Generating /lucene_solr_5_4_0/lucene/build/docs/queryparser/help-doc.html...
  [javadoc] Note: Custom tags that were not seen:  @lucene.internal, @lucene.experimental
  [javadoc] 2 warnings

BUILD FAILED
/lucene_solr_5_4_0/lucene/build.xml:244: The following error occurred while executing this line:
/lucene_solr_5_4_0/lucene/common-build.xml:2248: The following error occurred while executing this line:
/lucene_solr_5_4_0/lucene/module-build.xml:128: The following error occurred while executing this line:
/lucene_solr_5_4_0/lucene/queryparser/build.xml:35: The following error occurred while executing this line:
/lucene_solr_5_4_0/lucene/module-build.xml:78: The following error occurred while executing this line:
/lucene_solr_5_4_0/lucene/common-build.xml:2161: Javadocs warnings were found!

**Comment by tballison** [comment]
Fixed the javadocs.  Let me know if there are any other surprises.

**Comment by tballison** [comment]
Oh, and if you're (re)building 5.4.0...just to confirm...you've applied the patch to LUCENE-6929?

**Comment by modassar81** [comment]
Just to confirm. Is it that any SpanNotQuery will fail or only the wildcard in phrase with SpanNotQuery?
And the build got successful. Thanks Tim for the fix.

**Comment by modassar81** [comment]
Yes Tim. I have applied the patch to Lucene-6929.

**Comment by tballison** [comment]
Great.  The failure was: any MultiTerm (wildcard, fuzzy, prefix, range) within a SpanNotQuery where the exclude was not within the include (i.e. [fever bieber~1]!~2,2 : fever but not if bieber or variant appears 2 words before or after).

Thank you for raising this issue.
