### ISSUE TITLE
Different parsed queries.

### ISSUE THREAD

**Issue by modassar81** [tballison/lucene-addons#6]
Hi Tim,

I am trying to migrate to Solr-5.5.0 from Solr-5.4.0. When I test following query I am getting different parsed queries as follows:

Query       =>   (tt:((java OR book OR "java documents"~2 OR "java api"~>2)))
Solr-5.4.0  =>   (tt:java tt:book spanNear([tt:java, tt:document], 2, false) spanNear([tt:java, tt:api], 2, true))
Solr-5.5.0  =>   ((tt:java tt:book spanNear([tt:java, tt:document], 2, false) spanNear([tt:java, tt:api], 2, true))~4)

There is an extra slop of 4 added in Solr-5.5.0 parsed query. If I increase one more search term the slop appended at end also increases by one.
Can you please help me resolve this issue?

Thanks,
Modassar

**Comment by tballison** [comment]
Interesting.  Thank you for raising this.  Will take a look.

**Comment by tballison** [comment]
Hmmm...I'm not seeing it at the Lucene level:
    String qString = "(tt:((java OR book OR \"java documents\"~2 OR \"java api\"~>2)))";
    SpanQueryParser p = new SpanQueryParser(FIELD1, analyzer, multiTermAnalyzer);
    Query q = p.parse(qString);
    System.out.println(q.getClass() + " : " + q)

yields: 

class org.apache.lucene.search.BooleanQuery : tt:java tt:book spanNear([tt:java, tt:documents], 2, false) spanNear([tt:java, tt:api], 2, true)

Which branch are you using?  And is this the SpanOnlyQueryParser or the regular SpanQueryParser?

**Comment by modassar81** [comment]
I am using SpanQueryParser and lucene5.4on-0.1 branch. I am trying to debug it. Please let me know if there could be any relation with the Solr configuration which I think is not. But if required I can share the configuration details.

Thanks,
Modassar

**Comment by modassar81** [comment]
This was working fine with Lucene/Solr-5.4.0.

**Comment by tballison** [comment]
Oh, wait... is your default query parser operator set to "and"?

**Comment by modassar81** [comment]
The default query parser operator is set to AND. There is no explicit mention of mm in solrconfig.
I saw that there has been some change in the way mm is handled if explicit operator is given in edismax.
When I changed the query to (tt:((java book "java documents"~2 "java api"~>2))) I got following parsed query.
"parsedquery_toString": "+(+tt:java +tt:book +spanNear([tt:java, tt:document], 2, false) +spanNear([tt:java, tt:api], 2, true))",
I am using SpanQueryParser inside the edismax context for phrases.

**Comment by tballison** [comment]
Interesting...

> "parsedquery_toString": "+(+tt:java +tt:book +spanNear([tt:java, tt:document], 2, false) +spanNear([tt:java, tt:api], 2, true))",

Is this what you'd expect?  I'd think that the default query parser operator should only be operative if the user has not specified an OR query via parens.  Can't remember how the classic parser handles this.  I'll look into this.  

Most of my use cases have been default "OR" so I don't have many test cases for "AND"...again, will look.

If edismax is modifying the mm, I don't think there's anything I can do about that...unless you think the parser should set mm=1 for any OR query where the user doesn't specify mm...don't know if this will help or not.

**Comment by modassar81** [comment]
"parsedquery_toString": "+(+tt:java +tt:book +spanNear([tt:java, tt:document], 2, false) +spanNear([tt:java, tt:api], 2, true))",
Is this what you'd expect?
Yes Tim.

**Comment by modassar81** [comment]
This issue is logged in following jira ticket.
https://issues.apache.org/jira/browse/SOLR-8812

Best,
Modassar

**Comment by tballison** [comment]
Ah, ok, so this is not a problem with the SpanQueryParser?

**Comment by tballison** [comment]
If I understand correctly, this is an issue with Solr, not the SpanQueryParser.  Please reopen if I misunderstand.
