### ISSUE TITLE
Add syntax for SpanFirstQuery

### ISSUE THREAD

**Issue by nezda** [tballison/lucene-addons#7]
I rolled my own span query parser using https://pyparsing.wikispaces.com/ and I'd love to eventually get rid of it and use this.  One missing feature is syntax for SpanFirstQuery: I used "(sq1)<10" to mean sq1 matches within the first 10 terms of the document.  Any chance of adding a similar feature to this?

**Comment by tballison** [comment]
Y, that _should_ be fairly easy.  Could we get rid of the () and just use <\d+...or would it be too annoying to escape/singlequote '<; when it shows up within a term?

sq1<10  sq1 within first 10 terms
 (sq1 sq2)<10 -- sq1 or sq2 in the first 10 terms
"sq1 sq2"~4<10 -- sq1 within 4 of sq2 and that hit is within first 10 terms
[sq1 sq2]~4<10 -- sq1 within 4 of sq2 and that hit is within first 10 terms

'sq1<10'  -- term 'sq1<10'

**Comment by nezda** [comment]
👍  I'm good with all of that!

**Comment by tballison** [comment]
I'm starting to think that boosts and <n should be able to appear in either order.  It'll prob take a week or two to find the time to make this change.

**Comment by nezda** [comment]
Removing that modifier order dependency would make it a little easier to use.

**Comment by tballison** [comment]
Other thing I'm wondering...given that the goal of this parser is to expose as much available functionality of Spans as possible.

Should we add SpanPositionRange more generally?

cat<10 -- cat within the first 10
cat<10,20> -- cat btwn tokens 10 and 20
cat<10> -- cat after 10

We can't use >10 because this would be ambiguous:
"cat dog"~>10 -- could be 
"cat dog"~ >10 - phrase inorder=false after the 10th token
or
"cat dog"~>10 - phrase inorder=true with slop of 10
cat 

Is there a better/more intuitive syntax?

**Comment by nezda** [comment]
Oops, just noticed this.  Maybe perl-style range: cat@10..20 where either end is optional (e.g., cat@..20 or cat@10..)

**Comment by nezda** [comment]
If end is exclusive then maybe more like the Swift range operator syntax cat@10..<20  http://oleb.net/blog/2015/09/swift-ranges-and-intervals/

**Comment by tballison** [comment]
Back from leave, sorry for delay.

This looks great.  Thank you. Should have time to work on this tomorrow.

**Comment by tballison** [comment]
This should work now in the 5.5-0.2 branch. 

@nezda, thank you for the recommendation on the syntax. 

Let me know if there are any surprises.

**Comment by tballison** [comment]
I merged this modification into the 6.0-0.1 branch; and I also got that branch actually working with 6.0 at least for LUCENE-5205 and SOLR-5410...more work remains on the concordance code (LUCENE-5317) in 6.0...

**Comment by nezda** [comment]
@tballison sorry for my delayed response: this is really cool - thank you!

**Comment by tballison** [comment]
Enjoy, try to break it.
