### ISSUE TITLE
Compilation fails with java doc related issues.

### ISSUE THREAD

**Issue by modassar81** [tballison/lucene-addons#8]
Hi Tim,

How are you?

The compilation of SpanQueryParser is failing for branch lucene5.4on-0.1 when compiled with openjdk version "1.8.0_91". Please let me know if you have any plan for its fix in the mentioned branch or should I move to Solr-6 or higher.

Thanks,
Modassar

**Comment by tballison** [comment]
Great to hear from you Modassar. 

I just fixed the javadocs from 5.4 up through trunk.  I would recommend at the very least moving to 5.5-0.2.  That includes new syntax for SpanFirstQueries.

Let me know what else you find.  :)

Thank you for raising this issue.
