### ISSUE TITLE
Issue during compilation.

### ISSUE THREAD

**Issue by modassar81** [tballison/lucene-addons#9]
Hi Tim,

I am building solr-6.1.0 with lucene-addons-lucene6.0-0.1. openjdk version "1.8.0_91" is used.
Getting following errors. A few of them are:
/solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:82: error: bad use of '>'
* <li> Can require "in order" for phrases with slop with the ~> defaultOperator: &quot;jakarta apache&quot;~>3</li>

solr-6.1.0/lucene/core/src/java/org/apache/lucene/search/spans/SimpleSpanQueryConverter.java:36: error: self-closing element not allowed
* <p/>

/solr-6.1.0/lucene/core/src/java/org/apache/lucene/search/spans/SimpleSpanQueryConverter.java:55: error: unexpected text
* @throws java.io.IOException, IllegalArgumentException

Please look into it.

Thanks,
Modassar

**Comment by tballison** [comment]
I just fixed the version number in the 6.1-0.1 branch.  Give that a try.

**Comment by modassar81** [comment]
Thanks Tim for the fix. I am still getting following errors during compilation.

`solr-6.1.0/lucene/core/src/java/org/apache/lucene/search/spans/SimpleSpanQueryConverter.java:36: error: self-closing element not allowed
    <p/>`

`Compiling 23 source files to solr-6.1.0/lucene/build/queryparser/classes/java
solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:82: error: bad use of '>'
  <li> Can require "in order" for phrases with slop with the ~> defaultOperator: &quot;jakarta apache&quot;~>3</li>`
                                                               ^
`solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:82: error: bad use of '>'
  <li> Can require "in order" for phrases with slop with the ~> defaultOperator: &quot;jakarta apache&quot;~>3</li>`
                                                                                                             ^
`solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:86: error: bad use of '>'
  <li> Fully recursive phrasal queries with [ and ]; as in: [[jakarta apache]~3 lucene]~>4 :: `
                                                                                         ^
`solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:107: error: bad use of '>'
  in fuzzy queries: jakarta~1 (OSA) vs jakarta~>1 (Levenshtein)</li>`
                                                ^
`solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:136: error: bad use of '>'
  For example, "walked the dog" is converted to "walked dog"~>1 behind the scenes.  Like the Classic`
                                                              ^
`solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:141: warning: empty <p> tag
  <p>`

`solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:153: error: bad use of '>'
  <li>Fuzzy queries with slop > 2 are handled by SlowFuzzyQuery.  The developer can set the minFuzzySim to limit`
                               ^
`solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:155: error: bad use of '>'
  <li>Fuzzy queries with edit distance >=1 are rounded so that an exception is not thrown.</li>`
                                        ^
`Compiling 23 source files to solr-6.1.0/lucene/build/queryparser/classes/java
solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:84: error: text not allowed in <ul> element
  10 words after it.</li>`
                          
`solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:86: error: unexpected end tag: </li>
  words before &quot;lucene&quot;.</li>'`
                                   
`solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:137: warning: empty <p> tag
  <p>`
   
`solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:148: error: text not allowed in <ul> element
  <ul>'`
       
`solr-6.1.0/lucene/queryparser/src/java/org/apache/lucene/queryparser/spans/SpanQueryParser.java:149: error: unexpected end tag: </li>`
  `the maximum edit distance (i.e. turn off SlowFuzzyQuery by setting fuzzyMinSim = 2.0f.</li>`

Please look into these issues.

Best,
Modassar

**Comment by tballison** [comment]
Duh.  Ok, y, need to escape some things and fix some elements.  I need to figure out how to have Intellij fail the build for these problems.  Will fix today.

**Comment by tballison** [comment]
I updated my 6.0, 6.1 and trunk branches.  Please give 6.1 a try.

**Comment by tballison** [comment]
Let me know if you are all set now.  Thank you!

**Comment by modassar81** [comment]
Thanks for the fix Tim. It compiles without any issue.

Best,
Modassar
